### ISSUE TITLE
Error showing icon and Fonts not found

### ISSUE THREAD

**Issue by silenoth** [larsurilch/laravue#1]
Hello
I get an error when trying to display the icons

![deepinscreenshot_seleccionar area_20180410021715](https://user-images.githubusercontent.com/5028565/38537615-f2ec2a10-3c65-11e8-9d71-da5f476e9453.png)

look for the fonts folder outside the public folder.
![deepinscreenshot_seleccionar area_20180410021737](https://user-images.githubusercontent.com/5028565/38537622-01938bee-3c66-11e8-8170-7d5933ffc22a.png)
![deepinscreenshot_seleccionar area_20180410022316](https://user-images.githubusercontent.com/5028565/38537651-2ee26548-3c66-11e8-98ae-9892f05dda88.png)

any solution?
regards

**Comment by larsurilch** [comment]
Hello silenoth,
The problem is being caused because of the url. I create a VirtualHost pointing to the Laravel public folder. Ex: http://codegeo.local -> /var/www/html/codegeo/public
Regards
